Repository anantdark/hangman, pull requests merged in 2022-10, with the labels that each got.

#1 Initialize function
  hangman-cli/hangman.py
  hangman-cli/wordgen.py
Labels: good first issue

#4 add full logic for hangman with code comments
  hangman-cli/five_letter_words.txt
  hangman-cli/hangman.py
  hangman-cli/wordgen.py
Labels: enhancement

#11 Added requirements.txt
  requirements.txt
Labels: documentation, hacktoberfest-accepted

#7 GUI Version of Hangman
  hangman-GUI/hangman0.png
  hangman-GUI/hangman1.png
  hangman-GUI/hangman2.png
  hangman-GUI/hangman3.png
  hangman-GUI/hangman4.png
  hangman-GUI/hangman5.png
  hangman-GUI/hangman6.png
  hangman-GUI/main.py
  hangman-GUI/wordsStore.py
Labels: question

#23 Derive common five-letter words from Brown corpus
  words/five_letter_words.txt
Labels: question

#34 Add word definition cli
  hangman-cli/hangman.py
Labels: hacktoberfest-accepted, hacktoberfest

#35 Merge GUI and CLI
  hangman_cli/hangman.py
  hangman_gui/hangman0.png
  hangman_gui/hangman1.png
  hangman_gui/hangman2.png
  hangman_gui/hangman3.png
  hangman_gui/hangman4.png
  hangman_gui/hangman5.png
  hangman_gui/hangman6.png
  hangman_gui/main.py
  main.py
Labels: hacktoberfest
